/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFormularios;

import java.text.DecimalFormat;
import javax.swing.DefaultListCellRenderer.UIResource;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import pClases.Venta;

/**
 *
 * @author Multi
 */
public class FrmVenta extends javax.swing.JFrame {
    DefaultListModel modNumero = new DefaultListModel();
    DefaultListModel modDescripcion = new DefaultListModel();
    DefaultListModel modPrecio = new DefaultListModel();
    DefaultListModel modCantidad = new DefaultListModel();
    DefaultListModel modSubtotal = new DefaultListModel();
    
    //Formateo para decimales
    DecimalFormat df;
    
    //Número de producto
    int num;
    
    
    /**
     * Creates new form FrmVenta
     */
    public FrmVenta() {
        initComponents();
        cargaProductos();
        df = new DecimalFormat("###0.00");
    }
    
    void cargaProductos(){
        cboProducto.addItem("Cuadernos LayConsa");
        cboProducto.addItem("Cuadernos Justus");
        cboProducto.addItem("Cuadernos StanFord");
        cboProducto.addItem("Cuadernos David");
        cboProducto.addItem("Cuadernos College");
        cboProducto.addItem("Cuadernos Alpha");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitVen = new javax.swing.JLabel();
        cboProducto = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        btnComprar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNumProd = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstDescripcion = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstSubtotal = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstPrecio = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstCantidad = new javax.swing.JList<>();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblTitSub = new javax.swing.JLabel();
        lblTitDesc = new javax.swing.JLabel();
        lblTitTot = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitVen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitVen.setText("VENTA DE PRODUCTOS");

        cboProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("SELECCIONE PRODUCTO"));

        txtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("INGRESE CANTIDAD"));

        btnComprar.setText("COMPRAR");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        lstNumProd.setBorder(javax.swing.BorderFactory.createTitledBorder("NP"));
        jScrollPane1.setViewportView(lstNumProd);

        lstDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("DESCRIPCIÓN"));
        jScrollPane2.setViewportView(lstDescripcion);

        lstSubtotal.setBorder(javax.swing.BorderFactory.createTitledBorder("SUBTOTAL"));
        jScrollPane3.setViewportView(lstSubtotal);

        lstPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder("PRECIO"));
        jScrollPane4.setViewportView(lstPrecio);

        lstCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("CANT."));
        jScrollPane5.setViewportView(lstCantidad);

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblTitSub.setText("SUBTOTAL $");

        lblTitDesc.setText("DESCUENTO $");

        lblTitTot.setText("TOTAL $");

        lblSubtotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSubtotal.setText("0.00");
        lblSubtotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDescuento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDescuento.setText("0.00");
        lblDescuento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotal.setText("0.00");
        lblTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitVen)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitSub, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTitDesc, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTitTot, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitVen)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitSub)
                    .addComponent(lblSubtotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitDesc)
                            .addComponent(lblDescuento))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitTot)
                            .addComponent(lblTotal)))
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarControles();
        //Limpiando los modelos
        modNumero.removeAllElements();
        modDescripcion.removeAllElements();
        modPrecio.removeAllElements();
        modCantidad.removeAllElements();
        modSubtotal.removeAllElements();
        
        //Limpiando los controles
        lblSubtotal.setText("0.00");
        lblDescuento.setText("0.00");
        lblTotal.setText("0.00");
        
        num = 0;
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int r = JOptionPane.showOptionDialog(this, "Estas seguro de salir ...?", "Sistema de ventas", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(r == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        
        if(valida().equals("")){
            Venta objetoVenta = new Venta();
            
            //Enviando los valores
            objetoVenta.setCodigo(getProducto());
            objetoVenta.setDescripcion(getDescripcionProducto());
            objetoVenta.setCantidad(getCantidad());
            
            //Obtener los cálculos
            double precio = objetoVenta.asignaPrecio();
            double subtotal = objetoVenta.calculaSubtotal();
            
            //Imprimir en las listas
            imprimirListas(precio, subtotal);
            
            //Ubicar el valor en el lado derecho
            UIResource posicion = new UIResource();
            posicion.setHorizontalAlignment(SwingConstants.RIGHT);
            lstSubtotal.setCellRenderer(posicion);
            
            limpiarControles();
        
        }else{
            JOptionPane.showMessageDialog(null, "Error en " + valida());
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    //Método de validación
    String valida(){
        if(cboProducto.getSelectedIndex() == -1){
            cboProducto.requestFocus();
            return "Descripción del producto";
        }else if(txtCantidad.getText().equals("") || Integer.parseInt(txtCantidad.getText()) < 0){
            txtCantidad.setText("");
            txtCantidad.requestFocus();
            return "Cantidad comprada";
        }else{
            return "";
        }
    }
    
    
    void limpiarControles(){
        cboProducto.setSelectedIndex(0);
        txtCantidad.setText("");
        cboProducto.requestFocus();
    }
    
    void calculaTotales(){
        int n = modNumero.size();
        double subtotal = 0;
        
        for(int i = 0; i < n; i++){
            subtotal += Double.parseDouble(modSubtotal.getElementAt(i).toString());
        }
        
        double descuento = subtotal * 0.1;
        double neto = subtotal-descuento;
        
        lblSubtotal.setText(df.format(subtotal));
        lblDescuento.setText(df.format(descuento));
        lblTotal.setText(df.format(neto));
    }
    
    void imprimirListas(double precio, double subtotal){
        num++;
        modNumero.addElement(num);
        modDescripcion.addElement(getDescripcionProducto());
        modPrecio.addElement(df.format(precio));
        modCantidad.addElement(getCantidad());
        modSubtotal.addElement(df.format(subtotal));
        calculaTotales();
        
        lstNumProd.setModel(modNumero);
        lstDescripcion.setModel(modDescripcion);
        lstPrecio.setModel(modPrecio);
        lstCantidad.setModel(modCantidad);
        lstSubtotal.setModel(modSubtotal);
        
    }
    
    int getProducto(){
        return cboProducto.getSelectedIndex();
    }
    
    String getDescripcionProducto(){
        return String.valueOf(cboProducto.getSelectedItem());
    }
    
    int getCantidad(){
        return Integer.parseInt(txtCantidad.getText());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTitDesc;
    private javax.swing.JLabel lblTitSub;
    private javax.swing.JLabel lblTitTot;
    private javax.swing.JLabel lblTitVen;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList<String> lstCantidad;
    private javax.swing.JList<String> lstDescripcion;
    private javax.swing.JList<String> lstNumProd;
    private javax.swing.JList<String> lstPrecio;
    private javax.swing.JList<String> lstSubtotal;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
