/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFormularios;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import pClases.ArregloEmpleados;
import pClases.Empleado;

/**
 *
 * @author Multi
 */
public class FrmMantenimiento extends javax.swing.JFrame {

    ArregloEmpleados arrEmple = new ArregloEmpleados();
    
    DecimalFormat df;
    /**
     * Creates new form FrmMantenimiento
     */
    public FrmMantenimiento() {
        initComponents();
        
        btnGrabar.setVisible(false);
        df = new DecimalFormat("##0.00");
    }

    int getCodigo(){
        return Integer.parseInt(txtCodigo.getText());
    }
    
    String getEmpleado(){
        return txtEmpleado.getText();
    }
    
    int getHoras(){
        return Integer.parseInt(txtHoras.getText());
    }
    
    double getTarifa(){
        return Double.parseDouble(txtTarifa.getText());
    }
    
    void limpiaTabla(){
        for(int i = 0; i < 6; i++){
            tEmpleados.setValueAt("", i, 0);
            tEmpleados.setValueAt("", i, 1);
            tEmpleados.setValueAt("", i, 2);
            tEmpleados.setValueAt("", i, 3);
            tEmpleados.setValueAt("", i, 4);
        }
    }
    
    void listar(){
        limpiaTabla();
        for(int i = 0; i < arrEmple.getTamanio(); i++){
            tEmpleados.setValueAt(arrEmple.devolver(i).getCodigo(), i, 0);
            tEmpleados.setValueAt(arrEmple.devolver(i).getNombre(), i, 1);
            tEmpleados.setValueAt(arrEmple.devolver(i).getHoras(), i, 2);
            tEmpleados.setValueAt(arrEmple.devolver(i).getTarifa(), i, 3);
            tEmpleados.setValueAt(arrEmple.devolver(i).getTarifa() * 
                                  arrEmple.devolver(i).getHoras(), i, 4);
        }
    }
    
    String valida(){
        if(txtCodigo.getText().equals("") || Integer.parseInt(txtCodigo.getText()) <0){
            txtCodigo.requestFocus();
            return "Código del Empleado";
        }else if(txtEmpleado.getText().equals("")){
            txtEmpleado.requestFocus();
            return "Nombre del Empleado";
        }else if(txtHoras.getText().equals("") || Integer.parseInt(txtHoras.getText()) <0){
            txtHoras.requestFocus();
            return "Horas de trabajo";
        }else if(txtTarifa.getText().equals("") || Double.parseDouble(txtTarifa.getText()) <0){
            txtTarifa.requestFocus();
            return "Monto de la tarifa";
        }else{
            return "";
        }
    }
    
    void limpiarControles(){
        txtCodigo.setText("");
        txtEmpleado.setText("");
        txtHoras.setText("");
        txtTarifa.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtEmpleado = new javax.swing.JTextField();
        txtHoras = new javax.swing.JTextField();
        txtTarifa = new javax.swing.JTextField();
        btnListar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tEmpleados = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("MANTENIMIENTO DE EMPLEADOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 250, 14);

        txtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("CÓDIGO"));
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(10, 31, 159, 60);

        txtEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder("EMPLEADO"));
        getContentPane().add(txtEmpleado);
        txtEmpleado.setBounds(179, 31, 398, 60);

        txtHoras.setBorder(javax.swing.BorderFactory.createTitledBorder("HORAS"));
        getContentPane().add(txtHoras);
        txtHoras.setBounds(10, 100, 159, 60);

        txtTarifa.setBorder(javax.swing.BorderFactory.createTitledBorder("TARIFA"));
        getContentPane().add(txtTarifa);
        txtTarifa.setBounds(180, 100, 172, 60);

        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar);
        btnListar.setBounds(440, 110, 135, 40);

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(20, 200, 130, 37);

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(160, 200, 142, 37);

        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(310, 200, 130, 37);

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(450, 200, 130, 37);

        btnGrabar.setText("GRABAR");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrabar);
        btnGrabar.setBounds(160, 190, 140, 50);

        tEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Empleado", "Horario", "Tarifa", "Pago"
            }
        ));
        jScrollPane1.setViewportView(tEmpleados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 260, 567, 124);

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(10, 390, 173, 39);

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mantenimiento"));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 170, 580, 80);

        setBounds(0, 0, 615, 474);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            if (valida().equals("")) {
                Empleado objEmpleado = new Empleado(getCodigo(), getEmpleado(), getHoras(), getTarifa());
                
                arrEmple.adiciona(objEmpleado);
                limpiarControles();
                listar();
                
            } else {
                JOptionPane.showMessageDialog(null, "Error en: \n" + valida());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación!");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            limpiaTabla();
            
            int codigo = Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese código a buscar"));
            
            int pos = arrEmple.buscar(codigo);
            
            if(pos == -1)
                JOptionPane.showMessageDialog(null, "Código no existe");
            else{
                tEmpleados.setValueAt(arrEmple.devolver(pos).getCodigo(), 0, 0);
                tEmpleados.setValueAt(arrEmple.devolver(pos).getNombre(), 0, 1);
                tEmpleados.setValueAt(arrEmple.devolver(pos).getHoras(), 0, 2);
                tEmpleados.setValueAt(arrEmple.devolver(pos).getTarifa(), 0, 3);
                tEmpleados.setValueAt(arrEmple.devolver(pos).getTarifa() * 
                                  arrEmple.devolver(pos).getHoras(), 0, 4);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación!");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            int codigo = Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese código a eliminar"));
            
            arrEmple.eliminar(codigo);
            JOptionPane.showMessageDialog(null,"Empleado eliminado ...!");
            listar();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación!");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            
            int codigoB = Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese código a modificar"));
            
            int pos = arrEmple.buscar(codigoB);
            
            if (pos != -1) {
                Empleado x = arrEmple.devolver(pos);
                btnGrabar.setVisible(true);
                btnModificar.setVisible(false);
                
                txtCodigo.setText("" + codigoB);
                txtCodigo.setEditable(false);
                
                txtEmpleado.setText(x.getNombre());
                txtHoras.setText(""+x.getHoras());
                txtTarifa.setText(""+x.getTarifa());
                txtEmpleado.requestFocus();
                
            } else {
                JOptionPane.showMessageDialog(null, "Error en: \n" + valida());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación!");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        try {
            int pos = arrEmple.buscar(getCodigo());
            
            Empleado x = arrEmple.devolver(pos);
            
            x.setNombre(getEmpleado());
            x.setHoras(getHoras());
            x.setTarifa(getTarifa());
            JOptionPane.showMessageDialog(null, "Empleado actualizado correctamente",
                                        "Confirmación",JOptionPane.INFORMATION_MESSAGE);
            btnModificar.setVisible(true);
            btnGrabar.setVisible(false);
            listar();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al actualizar...!","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int r = JOptionPane.showOptionDialog(this, "Estas seguro de salir?", "Mantenimiento empleados", 
                                               JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(r == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tEmpleados;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtTarifa;
    // End of variables declaration//GEN-END:variables
}
