/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFormularios;

/**
 *
 * @author Multi
 */
public class FrmEstructurado extends javax.swing.JFrame {

    /**
     * Creates new form frmEstructurado
     */
    public FrmEstructurado() {
        initComponents();
        
        cboMoneda.addItem("PESOS");
        cboMoneda.addItem("DOLARES");
        
        cboBien.addItem("AUTOMOVIL");
        cboBien.addItem("VIVIENDA");
        cboBien.addItem("OTRO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitModelo = new javax.swing.JLabel();
        lblTitTipoM = new javax.swing.JLabel();
        lblTitTipoB = new javax.swing.JLabel();
        lblTitPlazoMe = new javax.swing.JLabel();
        lblTitValorB = new javax.swing.JLabel();
        cboMoneda = new javax.swing.JComboBox<>();
        cboBien = new javax.swing.JComboBox<>();
        txtMeses = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        lblTitTasaI = new javax.swing.JLabel();
        lblTitCuoIni = new javax.swing.JLabel();
        lblTasaInteres = new javax.swing.JLabel();
        lblInicial = new javax.swing.JLabel();
        btnResultados = new javax.swing.JButton();
        lblTitCuotaInicial = new javax.swing.JLabel();
        lblCuotaInicial = new javax.swing.JLabel();
        lblTitRiesNeto = new javax.swing.JLabel();
        lblRiesgo = new javax.swing.JLabel();
        lblTitCuotaMen = new javax.swing.JLabel();
        lblCuotaMensual = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modelo de cotización bancaria");

        lblTitModelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitModelo.setText("MODELO DE COTIZACION BANCARIA - ESTRUCTURADA");

        lblTitTipoM.setText("TIPO DE MONEDA");

        lblTitTipoB.setText("TIPO DE BIEN");

        lblTitPlazoMe.setText("PLAZO EN MESES");

        lblTitValorB.setText("VALOR DEL BIEN");

        cboMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMonedaActionPerformed(evt);
            }
        });

        lblTitTasaI.setText("TASA DE INTERES %");

        lblTitCuoIni.setText("CUOTA INICIAL %");

        lblTasaInteres.setText("12.00");

        lblInicial.setText("20.00");

        btnResultados.setText("VER RESULTADOS DE LA SIMULACIÓN");
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        lblTitCuotaInicial.setText("CUOTA INICIAL");

        lblCuotaInicial.setText("$0.00");

        lblTitRiesNeto.setText("RIESGO NETO");

        lblRiesgo.setText("$0.00");

        lblTitCuotaMen.setText("CUOTA MENSUAL");

        lblCuotaMensual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCuotaMensual.setText("$0.00");

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblTitModelo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitTipoM)
                                    .addComponent(lblTitTipoB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTitPlazoMe, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTitValorB, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboMoneda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboBien, 0, 100, Short.MAX_VALUE)
                                    .addComponent(txtMeses)
                                    .addComponent(txtValor))
                                .addGap(150, 150, 150)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTitTasaI)
                                    .addComponent(lblTitCuoIni))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTasaInteres)
                                    .addComponent(lblInicial)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTitCuotaInicial)
                                            .addGap(29, 29, 29)
                                            .addComponent(lblCuotaInicial)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblTitRiesNeto)
                                            .addGap(34, 34, 34)
                                            .addComponent(lblRiesgo)
                                            .addGap(16, 16, 16))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTitCuotaMen)
                                        .addComponent(lblCuotaMensual))
                                    .addGap(156, 156, 156)
                                    .addComponent(btnLimpiar))))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitModelo)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitTipoM)
                    .addComponent(cboMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitTipoB)
                    .addComponent(cboBien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitPlazoMe)
                    .addComponent(txtMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitTasaI)
                    .addComponent(lblTasaInteres))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitValorB)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitCuoIni)
                    .addComponent(lblInicial))
                .addGap(28, 28, 28)
                .addComponent(btnResultados)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitCuotaInicial)
                    .addComponent(lblCuotaInicial)
                    .addComponent(lblTitRiesNeto)
                    .addComponent(lblRiesgo))
                .addGap(23, 23, 23)
                .addComponent(lblTitCuotaMen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuotaMensual)
                    .addComponent(btnLimpiar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMonedaActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        // Entrada
        String moneda = String.valueOf(cboMoneda.getSelectedItem());
        String simbolo = moneda.equals("PESOS")? "$" : "USD $";
        
        String bien = String.valueOf(cboBien.getSelectedItem());
        
        int meses = Integer.parseInt(txtMeses.getText());
        double valor = Double.parseDouble(txtValor.getText());
        
        double tasa = Double.parseDouble(lblTasaInteres.getText());
        double inicial = Double.parseDouble(lblInicial.getText());
        
        //Proceso
        double cuotaInicial = valor * 0.2;
        double riesgo = valor - cuotaInicial;
        double cuotaMensual = (riesgo * 1.12) / meses;
        
        
        //Salida
        lblCuotaInicial.setText(simbolo + String.format("%.2f",cuotaInicial));
        lblRiesgo.setText(simbolo + String.format("%.2f",riesgo));
        lblCuotaMensual.setText(simbolo + String.format("%.2f",cuotaMensual));
        
        
        
        
    }//GEN-LAST:event_btnResultadosActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        cboMoneda.setSelectedIndex(0);
        cboBien.setSelectedIndex(0);
        
        txtMeses.setText("");
        txtValor.setText("");
        
        lblCuotaInicial.setText("$0.00");
        lblRiesgo.setText("$0.00");
        lblCuotaMensual.setText("$0.00");
        
        cboMoneda.requestFocus();
        
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEstructurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEstructurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEstructurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEstructurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEstructurado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnResultados;
    private javax.swing.JComboBox<String> cboBien;
    private javax.swing.JComboBox<String> cboMoneda;
    private javax.swing.JLabel lblCuotaInicial;
    private javax.swing.JLabel lblCuotaMensual;
    private javax.swing.JLabel lblInicial;
    private javax.swing.JLabel lblRiesgo;
    private javax.swing.JLabel lblTasaInteres;
    private javax.swing.JLabel lblTitCuoIni;
    private javax.swing.JLabel lblTitCuotaInicial;
    private javax.swing.JLabel lblTitCuotaMen;
    private javax.swing.JLabel lblTitModelo;
    private javax.swing.JLabel lblTitPlazoMe;
    private javax.swing.JLabel lblTitRiesNeto;
    private javax.swing.JLabel lblTitTasaI;
    private javax.swing.JLabel lblTitTipoB;
    private javax.swing.JLabel lblTitTipoM;
    private javax.swing.JLabel lblTitValorB;
    private javax.swing.JTextField txtMeses;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
