/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFormularios;

import java.text.DecimalFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import pClases.Arreglo;

/**
 *
 * @author Multi
 */
public class FrmCertamen extends javax.swing.JFrame {
    Arreglo arrCandidata = new Arreglo();
    
    DefaultListModel modCandidatas = new DefaultListModel();
    DefaultListModel modPromedio = new DefaultListModel();
    DefaultListModel modEstadisticas = new DefaultListModel();
    
    DecimalFormat df;
    
    /**
     * Creates new form FrmCertamen
     */
    public FrmCertamen() {
        initComponents();
        df = new DecimalFormat("#0.00");
    }

    String getNombre(){
        return txtCandidata.getText();
    }
    
    double getPuntaje1(){
        return Double.parseDouble(txtPuntaje1.getText());
    }
    
    double getPuntaje2(){
        return Double.parseDouble(txtPuntaje2.getText());
    }
    
    double getPuntaje3(){
        return Double.parseDouble(txtPuntaje3.getText());
    }
    
    double calculaPromedio(){
        return (getPuntaje1() + getPuntaje2() + getPuntaje3())/3.0;
    }
    
    void imprimir(){
        modCandidatas.clear();
        modPromedio.clear();
        modEstadisticas.clear();
        
        for (int i = 0; i < arrCandidata.totalCandidatas(); i++) {
            modCandidatas.addElement(arrCandidata.devuelveNombre(i));
            modPromedio.addElement(df.format(arrCandidata.devuelvePromedio(i)));
        }
        
        lstCandidatas.setModel(modCandidatas);
        lstPromedio.setModel(modPromedio);
    }
    
    void limpiar(){
        txtCandidata.setText("");
        txtPuntaje1.setText("");
        txtPuntaje2.setText("");
        txtPuntaje3.setText("");
        txtCandidata.requestFocus();
    }
    
    String valida(){
        if(txtCandidata.getText().equals("")){
            txtCandidata.requestFocus();
            return "Nombre de la candidata";
        }else if( txtPuntaje1.getText().equals("") ||
                  Double.parseDouble(txtPuntaje1.getText()) < 0 ||
                  Double.parseDouble(txtPuntaje1.getText()) > 100  ){
            txtPuntaje1.setText("");
            txtPuntaje1.requestFocus();
            return "Puntaje 1";
        }else if( txtPuntaje2.getText().equals("") ||
                  Double.parseDouble(txtPuntaje2.getText()) < 0 ||
                  Double.parseDouble(txtPuntaje2.getText()) > 100  ){
            txtPuntaje2.setText("");
            txtPuntaje2.requestFocus();
            return "Puntaje 2";
        }else if( txtPuntaje3.getText().equals("") ||
                  Double.parseDouble(txtPuntaje3.getText()) < 0 ||
                  Double.parseDouble(txtPuntaje3.getText()) > 100  ){
            txtPuntaje3.setText("");
            txtPuntaje3.requestFocus();
            return "Puntaje 3";
        }else{
            return "";
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitCert = new javax.swing.JLabel();
        txtCandidata = new javax.swing.JTextField();
        txtPuntaje1 = new javax.swing.JTextField();
        txtPuntaje2 = new javax.swing.JTextField();
        txtPuntaje3 = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCandidatas = new javax.swing.JList<>();
        btnEstadisticas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPromedio = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstEstadisticas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitCert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitCert.setText("CERTAMEN DE BELLEZA");

        txtCandidata.setBorder(javax.swing.BorderFactory.createTitledBorder("Candidata"));

        txtPuntaje1.setBorder(javax.swing.BorderFactory.createTitledBorder("Puntaje 1"));

        txtPuntaje2.setBorder(javax.swing.BorderFactory.createTitledBorder("Puntaje 2"));

        txtPuntaje3.setBorder(javax.swing.BorderFactory.createTitledBorder("Puntaje 3"));

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lstCandidatas.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de candidatas"));
        jScrollPane1.setViewportView(lstCandidatas);

        btnEstadisticas.setText("ESTADÍSTICAS");
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstPromedio);

        jScrollPane3.setViewportView(lstEstadisticas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblTitCert))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCandidata, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPuntaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPuntaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPuntaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnEstadisticas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(0, 15, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitCert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCandidata, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPuntaje1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(txtPuntaje2)
                    .addComponent(txtPuntaje3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            if(valida().equals("")){
                String candidata = getNombre();
                double puntaje1 = getPuntaje1();
                double puntaje2 = getPuntaje2();
                double puntaje3 = getPuntaje3();
                
                arrCandidata.registraCandidata(candidata, calculaPromedio());
                imprimir();
                limpiar();
            }else{
                JOptionPane.showMessageDialog(null, "Error en: \n" + valida());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        int total = arrCandidata.totalCandidatas();
        modEstadisticas.clear();
        modEstadisticas.addElement("El total de candidatas es: " + total);
        modEstadisticas.addElement("El máximo puntaje es: " + df.format(arrCandidata.puntajeAlto()));
        modEstadisticas.addElement("La ganadora es: " + arrCandidata.ganadora());
        
        lstEstadisticas.setModel(modEstadisticas);
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCertamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCertamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCertamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCertamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCertamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTitCert;
    private javax.swing.JList<String> lstCandidatas;
    private javax.swing.JList<String> lstEstadisticas;
    private javax.swing.JList<String> lstPromedio;
    private javax.swing.JTextField txtCandidata;
    private javax.swing.JTextField txtPuntaje1;
    private javax.swing.JTextField txtPuntaje2;
    private javax.swing.JTextField txtPuntaje3;
    // End of variables declaration//GEN-END:variables
}
