/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFormularios;

import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import pClases.ArregloEstudiantes;
import pClases.Estudiante;

/**
 *
 * @author Multi
 */
public class FrmMantenimiento extends javax.swing.JFrame {

    ArregloEstudiantes arrEstudiantes = new ArregloEstudiantes();
    
    /**
     * Creates new form FrmMantenimiento
     */
    public FrmMantenimiento() {
        initComponents();
        defineAnchoTabla();
        
        llenaCombo();
        
        listar();
        btnGrabarIng.setVisible(false);
        btnGrabarMod.setVisible(false);
        habilitaCajas(false);
        
    }
    
    void defineAnchoTabla(){
        TableColumn columna;
        columna = tAlumnos.getColumnModel().getColumn(0);
        columna.setPreferredWidth(50);
        columna = tAlumnos.getColumnModel().getColumn(1);
        columna.setPreferredWidth(150);
        columna = tAlumnos.getColumnModel().getColumn(2);
        columna.setPreferredWidth(30);
        columna = tAlumnos.getColumnModel().getColumn(3);
        columna.setPreferredWidth(40);
        tAlumnos.getTableHeader().setReorderingAllowed(false);
        tAlumnos.getTableHeader().setResizingAllowed(false);
    }
    
    void llenaCombo(){
        cboCiclo.addItem("1");
        cboCiclo.addItem("2");
        cboCiclo.addItem("3");
        cboCiclo.addItem("4");
        cboCiclo.addItem("5");
        cboCiclo.addItem("6");
    }
    
    void habilitaCajas(boolean opcion){
        txtCodigo.setEditable(opcion);
        txtNombres.setEditable(opcion);
        txtPension.setEditable(opcion);
        cboCiclo.setEnabled(opcion);
    }
    
    void limpiaCajas(){
        txtCodigo.setText("");
        txtNombres.setText("");
        txtPension.setText("");
        cboCiclo.setSelectedIndex(0);
    }
    
    void limpiaMatriz(){
        for (int i = 0; i < 15; i++) {
            tAlumnos.setValueAt("", i, 0);
            tAlumnos.setValueAt("", i, 1);
            tAlumnos.setValueAt("", i, 2);
            tAlumnos.setValueAt("", i, 3);
        }
    }
    
    public int autogeneraCodigo(){
        int cod = (int) ((9999-1000+1) * Math.random() + 1000);
        return cod;
    }
    
    void listar(){
        if(arrEstudiantes.getTamanio() > 0){
            for (int i = 0; i < arrEstudiantes.getTamanio(); i++) {
                Estudiante e = arrEstudiantes.obtener(i);
                tAlumnos.setValueAt(e.getCodigo(), i, 0);
                tAlumnos.setValueAt(e.getNombre(), i, 1);
                tAlumnos.setValueAt(e.getCiclo(), i, 2);
                tAlumnos.setValueAt(e.getPension(), i, 3);
            }
        }
    }
    
    public int getCodigo(){
        return Integer.parseInt(txtCodigo.getText());
    }
    
    public String getNombre(){
        return txtNombres.getText();
    }
    
    public double getPension(){
        return Double.parseDouble(txtPension.getText());
    }
    
    public int getCiclo(){
        return cboCiclo.getSelectedIndex()+1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitMant = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        cboCiclo = new javax.swing.JComboBox<>();
        txtPension = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnGrabarIng = new javax.swing.JButton();
        btnGrabarMod = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAlumnos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitMant.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTitMant.setText("MANTENIMIENTO DE ALUMNOS");

        txtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("CÓDIGO"));

        txtNombres.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRES Y APELLIDOS"));

        cboCiclo.setBorder(javax.swing.BorderFactory.createTitledBorder("CICLO"));

        txtPension.setBorder(javax.swing.BorderFactory.createTitledBorder("PENSIÓN"));

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnGrabarIng.setText("GRABAR ING");
        btnGrabarIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarIngActionPerformed(evt);
            }
        });

        btnGrabarMod.setText("GRABAR MOD");
        btnGrabarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarModActionPerformed(evt);
            }
        });

        tAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOMBRES Y APELLIDOS", "CICLO", "PENSIÓN"
            }
        ));
        jScrollPane1.setViewportView(tAlumnos);
        if (tAlumnos.getColumnModel().getColumnCount() > 0) {
            tAlumnos.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(lblTitMant))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPension, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGrabarIng, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGrabarMod, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnGrabarIng, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGrabarMod, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitMant)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPension, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            limpiaCajas();
            limpiaMatriz();
            
            int codigo = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese código a buscar:"));
            
            Estudiante e = arrEstudiantes.buscar(codigo);
            
            if(e != null){
                tAlumnos.setValueAt(e.getCodigo(), 0, 0);
                tAlumnos.setValueAt(e.getNombre(), 0, 1);
                tAlumnos.setValueAt(e.getCiclo(), 0, 2);
                tAlumnos.setValueAt(e.getPension(), 0, 3);
            }else{
                JOptionPane.showMessageDialog(null, "Código de estudiantes NO existe");
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de datos");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        int codigo = autogeneraCodigo();
        txtCodigo.setText(""+codigo);
        habilitaCajas(true);
        txtCodigo.setEditable(false);
        txtNombres.requestFocus();
        btnGrabarIng.setVisible(true);
        btnIngresar.setVisible(false);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int codigo = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese código de estudiante a modificar:"));
        
        habilitaCajas(true);
        limpiaMatriz();
        txtCodigo.setEditable(false);
        
        Estudiante e = arrEstudiantes.buscar(codigo);
        
        if(e != null){
            txtCodigo.setText("" + e.getCodigo());
            txtNombres.setText(e.getNombre());
            txtPension.setText(""+e.getPension());
            cboCiclo.setSelectedIndex(e.getCiclo()-1);
            
            btnGrabarMod.setVisible(true);
            btnModificar.setVisible(false);
            
        }else{
            JOptionPane.showMessageDialog(null, "Código de estudiantes NO existe");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            limpiaCajas();
            limpiaMatriz();
            
            int codigo = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese código a eliminar:"));
            
            Estudiante e = arrEstudiantes.buscar(codigo);
            
            if(e != null){
                arrEstudiantes.eliminar(e);
                arrEstudiantes.grabar();
                listar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Código de estudiante no existe");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnGrabarModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarModActionPerformed
        try{    
            Estudiante e = arrEstudiantes.buscar(getCodigo());
            if(e != null){
                e.setNombre(getNombre());
                e.setCiclo(getCiclo());
                e.setPension(getPension());

                arrEstudiantes.grabar();
                listar();
            }
            limpiaCajas();
            habilitaCajas(false);

            btnModificar.setVisible(true);
            btnGrabarMod.setVisible(false);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación: " + e);
        }
    }//GEN-LAST:event_btnGrabarModActionPerformed

    private void btnGrabarIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarIngActionPerformed
        try{    
            Estudiante e = arrEstudiantes.buscar(getCodigo());
            if(e == null){
                e = new Estudiante(getCodigo(), getNombre(), getCiclo(), getPension());

                arrEstudiantes.adicionar(e);
                arrEstudiantes.grabar();
                listar();
            }
            limpiaCajas();
            habilitaCajas(false);

            btnIngresar.setVisible(true);
            btnGrabarIng.setVisible(false);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación: " + e);
        }
    }//GEN-LAST:event_btnGrabarIngActionPerformed
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabarIng;
    private javax.swing.JButton btnGrabarMod;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cboCiclo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitMant;
    private javax.swing.JTable tAlumnos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPension;
    // End of variables declaration//GEN-END:variables
}
