/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFormularios;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import pClases.Participantes;

/**
 *
 * @author Multi
 */
public class FrmParticipantes extends javax.swing.JFrame {
    DefaultListModel modResumen = new DefaultListModel();

    /**
     * Creates new form FrmParticipantes
     */
    public FrmParticipantes() {
        initComponents();
    }
    
    String valida(){
        if( txtEdad.getText().equals("") || Integer.parseInt(txtEdad.getText()) < 0 ){
            return "Edad del asistente ...!!!";
        } else if ( !( rbSoltero.isSelected() || rbCasado.isSelected() 
                    || rbViudo.isSelected() || rbDivorciado.isSelected() ) ){
            return "Estado civil del asistente...!!!";
        }else{
            return "";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgEstadoCivil = new javax.swing.ButtonGroup();
        lblTitPart = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        btnProcesar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        chkMasculino = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstResumen = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        rbSoltero = new javax.swing.JRadioButton();
        rbCasado = new javax.swing.JRadioButton();
        rbViudo = new javax.swing.JRadioButton();
        rbDivorciado = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitPart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitPart.setText("REGISTRO DE PARTICIPANTES");

        txtEdad.setBorder(javax.swing.BorderFactory.createTitledBorder("INGRESE EDAD"));

        btnProcesar.setText("PROCESAR");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        chkMasculino.setText("Masculino");

        jScrollPane1.setViewportView(lstResumen);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ESTADO CIVIL"));

        btgEstadoCivil.add(rbSoltero);
        rbSoltero.setText("SOLTERO");

        btgEstadoCivil.add(rbCasado);
        rbCasado.setText("CASADO");

        btgEstadoCivil.add(rbViudo);
        rbViudo.setText("VIUDO");

        btgEstadoCivil.add(rbDivorciado);
        rbDivorciado.setText("DIVORCIADO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSoltero)
                    .addComponent(rbCasado)
                    .addComponent(rbViudo)
                    .addComponent(rbDivorciado))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rbSoltero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCasado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbViudo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbDivorciado)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitPart)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkMasculino)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(btnProcesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitPart)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(chkMasculino)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 195, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        if(valida().equals("")){
            Participantes objParticipantes = new Participantes();
            
            //Enviando información a la clase
            objParticipantes.setEdad(Integer.parseInt(txtEdad.getText()));
            if(chkMasculino.isSelected()){
                objParticipantes.setSexo("Masculino");
            }else{
                objParticipantes.setSexo("Femenino");
            }
            
            if(rbSoltero.isSelected()){
                objParticipantes.setEstadoCivil("Soltero");
            } else if(rbCasado.isSelected()){
                objParticipantes.setEstadoCivil("Casado");
            } else if(rbViudo.isSelected()){
                objParticipantes.setEstadoCivil("Viudo");
            } else {
                objParticipantes.setEstadoCivil("Divorciado");
            }
            
            //Invocando los conteos
            objParticipantes.determinaEdad();
            objParticipantes.determinaSexo();
            objParticipantes.determinaEstado();
            
            //Obtener los resultados
            int total = objParticipantes.getTotal();
            int totalMayor = Participantes.gettMayores();
            int totalMenor = Participantes.gettMenores();
            int totalHombres = Participantes.gettHombres();
            int totalMujeres = Participantes.gettMujeres();
            int totalSolteros = Participantes.gettSolteros();
            int totalCasados = Participantes.gettCasados();
            int totalViudos = Participantes.gettViudos();
            int totalDivorciados = Participantes.gettDivorciados();
            int porcentajeHombres = (totalHombres * 100) / total;
            int porcentajeMujeres = (totalMujeres * 100) / total;
            
            //Mostrar los resultados
            modResumen.clear();
            modResumen.addElement("** ESTADÍSTICAS **");
            modResumen.addElement("El total de asistentes es: " + total);
            modResumen.addElement("El total de personas mayores es: " + totalMayor);
            modResumen.addElement("El total de personas menores es: " + totalMenor);
            modResumen.addElement("-----------------------------");
            modResumen.addElement("El total de hombres es: " + totalHombres);
            modResumen.addElement("El total de mujeres es: " + totalMujeres);
            modResumen.addElement("-----------------------------");
            modResumen.addElement("El total de solteros es: " + totalSolteros);
            modResumen.addElement("El total de casados es: " + totalCasados);
            modResumen.addElement("El total de viudos es: " + totalViudos);
            modResumen.addElement("El total de divorciados es: " + totalDivorciados);
            modResumen.addElement("-----------------------------");
            modResumen.addElement("% de hombres: " + porcentajeHombres);
            modResumen.addElement("% de mujeres: " + porcentajeMujeres);
            
            lstResumen.setModel(modResumen);
            
        
        }else{
            JOptionPane.showMessageDialog(null, "El problema es: \n" + valida());
        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int r = JOptionPane.showOptionDialog(this, "Estas seguro de salir ...?", "Control de participantes", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(r == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtEdad.setText("");
        chkMasculino.setSelected(false);
        btgEstadoCivil.clearSelection();
        
        modResumen.clear();
        txtEdad.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmParticipantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgEstadoCivil;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkMasculino;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitPart;
    private javax.swing.JList<String> lstResumen;
    private javax.swing.JRadioButton rbCasado;
    private javax.swing.JRadioButton rbDivorciado;
    private javax.swing.JRadioButton rbSoltero;
    private javax.swing.JRadioButton rbViudo;
    private javax.swing.JTextField txtEdad;
    // End of variables declaration//GEN-END:variables
}
