/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFormularios;

/**
 *
 * @author Multi
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpMenu = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mListado = new javax.swing.JMenu();
        miGeneraProductos = new javax.swing.JMenuItem();
        miProductosCategoria = new javax.swing.JMenuItem();
        miProductosPrecio = new javax.swing.JMenuItem();
        mMantenimiento = new javax.swing.JMenu();
        miNuevoProducto = new javax.swing.JMenuItem();
        miModificaProducto = new javax.swing.JMenuItem();
        miEliminaProducto = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenu();
        miSi = new javax.swing.JMenuItem();
        miNo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpMenuLayout = new javax.swing.GroupLayout(dpMenu);
        dpMenu.setLayout(dpMenuLayout);
        dpMenuLayout.setHorizontalGroup(
            dpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        dpMenuLayout.setVerticalGroup(
            dpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        mListado.setText("LISTADO");

        miGeneraProductos.setText("GENERAL DE PRODUCTOS");
        miGeneraProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGeneraProductosActionPerformed(evt);
            }
        });
        mListado.add(miGeneraProductos);

        miProductosCategoria.setText("PRODUCTOS POR CATEGORIA");
        miProductosCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProductosCategoriaActionPerformed(evt);
            }
        });
        mListado.add(miProductosCategoria);

        miProductosPrecio.setText("PRODUCTOS POR PRECIO");
        miProductosPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProductosPrecioActionPerformed(evt);
            }
        });
        mListado.add(miProductosPrecio);

        menuBar.add(mListado);

        mMantenimiento.setText("MANTENIMIENTO");

        miNuevoProducto.setText("NUEVO PRODUCTO");
        miNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNuevoProductoActionPerformed(evt);
            }
        });
        mMantenimiento.add(miNuevoProducto);

        miModificaProducto.setText("MODIFICA PRODUCTO");
        mMantenimiento.add(miModificaProducto);

        miEliminaProducto.setText("ELIMINA PRODUCTO");
        mMantenimiento.add(miEliminaProducto);

        menuBar.add(mMantenimiento);

        mSalir.setText("SALIR");

        miSi.setText("SI");
        mSalir.add(miSi);

        miNo.setText("NO");
        mSalir.add(miNo);

        menuBar.add(mSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miGeneraProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGeneraProductosActionPerformed
        
        frmGeneralProductos objG = new frmGeneralProductos();
        
        dpMenu.add(objG);
        objG.show();
    }//GEN-LAST:event_miGeneraProductosActionPerformed

    private void miNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNuevoProductoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_miNuevoProductoActionPerformed

    private void miProductosCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductosCategoriaActionPerformed
        // TODO add your handling code here:
        frmProductosCategoria objC = new frmProductosCategoria();
        
        dpMenu.add(objC);
        objC.show();
    }//GEN-LAST:event_miProductosCategoriaActionPerformed

    private void miProductosPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductosPrecioActionPerformed
        // TODO add your handling code here:
        frmProductosPrecio objP = new frmProductosPrecio();
        
        dpMenu.add(objP);
        objP.show();
    }//GEN-LAST:event_miProductosPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpMenu;
    private javax.swing.JMenu mListado;
    private javax.swing.JMenu mMantenimiento;
    private javax.swing.JMenu mSalir;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miEliminaProducto;
    private javax.swing.JMenuItem miGeneraProductos;
    private javax.swing.JMenuItem miModificaProducto;
    private javax.swing.JMenuItem miNo;
    private javax.swing.JMenuItem miNuevoProducto;
    private javax.swing.JMenuItem miProductosCategoria;
    private javax.swing.JMenuItem miProductosPrecio;
    private javax.swing.JMenuItem miSi;
    // End of variables declaration//GEN-END:variables
}
