/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFormularios;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import pClases.Libro;

/**
 *
 * @author Multi
 */
public class FrmRegistro extends javax.swing.JFrame {
    
    Libro objLibro;
    
    DefaultListModel modLibro, modEditorial, modClase, modAnio, modPaginas, modCosto;
    DefaultListModel modEstadisticas;
    
    /**
     * Creates new form FrmRegistro
     */
    public FrmRegistro() {
        initComponents();
        
        llenaEditorial();
        llenaClase();
        
        cargaModelos();
    }
    
    void cargaModelos(){
        modLibro = new DefaultListModel();
        modEditorial = new DefaultListModel(); 
        modClase = new DefaultListModel(); 
        modAnio = new DefaultListModel(); 
        modPaginas = new DefaultListModel(); 
        modCosto = new DefaultListModel();
        
        modEstadisticas = new DefaultListModel();
        
        lstLibro.setModel(modLibro);
        lstEditorial.setModel(modEditorial);
        lstClase.setModel(modClase);
        lstAnio.setModel(modAnio);
        lstPaginas.setModel(modPaginas);
        lstCosto.setModel(modCosto);
        
        lstEstadisticas.setModel(modEstadisticas);
    
    }
    
    void llenaModelos(){
        modLibro.addElement(objLibro.getNombre());
        modEditorial.addElement(objLibro.getEditorial()); 
        modClase.addElement(objLibro.getClase()); 
        modAnio.addElement(objLibro.getAnio()); 
        modPaginas.addElement(objLibro.getPaginas()); 
        modCosto.addElement(objLibro.getCosto());
    }
    
    void llenaEstadisticas(){
        modEstadisticas.addElement("Número de libros de Análisis de edición B: " + Libro.gettAnalisisB());
        modEstadisticas.addElement("Libro de edición más reciente: " + Libro.getEdicionMasReciente());
        modEstadisticas.addElement("Editorial con libro de menor páginas: " + Libro.getEditorialMenorPaginas());
        modEstadisticas.addElement("Libro con mayor costo: " + Libro.getLibroMayorCosto());
    }
    
    
    void llenaEditorial(){
        cboEditorial.addItem("A");
        cboEditorial.addItem("B");
        cboEditorial.addItem("C");
    }
    
    void llenaClase(){
        cboClase.addItem("Programación");
        cboClase.addItem("Análisis");
        cboClase.addItem("Diseño");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitReg = new javax.swing.JLabel();
        cboEditorial = new javax.swing.JComboBox<>();
        cboClase = new javax.swing.JComboBox<>();
        txtLibro = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtPaginas = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLibro = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEditorial = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstClase = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstAnio = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstPaginas = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstCosto = new javax.swing.JList<>();
        btnEstadisticas = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstEstadisticas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa de registro de libros");

        lblTitReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitReg.setText("REGISTRO DEL LIBRO");

        cboEditorial.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de editorial"));

        cboClase.setBorder(javax.swing.BorderFactory.createTitledBorder("Clase de libro"));

        txtLibro.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre del libro"));

        txtAnio.setBorder(javax.swing.BorderFactory.createTitledBorder("Año de Edición"));

        txtPaginas.setBorder(javax.swing.BorderFactory.createTitledBorder("Páginas"));

        txtCosto.setBorder(javax.swing.BorderFactory.createTitledBorder("Costo"));

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstLibro);

        jScrollPane2.setViewportView(lstEditorial);

        jScrollPane3.setViewportView(lstClase);

        jScrollPane4.setViewportView(lstAnio);

        jScrollPane5.setViewportView(lstPaginas);

        jScrollPane6.setViewportView(lstCosto);

        btnEstadisticas.setText("ESTADISTICAS");
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });

        jScrollPane7.setViewportView(lstEstadisticas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane7)
                    .addComponent(btnEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCosto))
                            .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cboClase, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(lblTitReg)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboClase)
                    .addComponent(cboEditorial)
                    .addComponent(txtLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCosto, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(txtPaginas)
                    .addComponent(txtAnio)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try{
            objLibro = new Libro(getLibro(),getEditorial(),getClase(),getAnio(),getPaginas(),getCosto());
            llenaModelos();
            objLibro.masReciente();
            objLibro.menorPaginas();
            objLibro.mayorCosto();
            
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error en la aplicación: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        try{
            modEstadisticas.clear();
            llenaEstadisticas();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error en la aplicación: " + ex.getMessage());
            
        }
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtLibro.setText("");
        
        cboClase.setSelectedIndex(0);
        cboEditorial.setSelectedIndex(0);
        
        txtAnio.setText("");
        txtPaginas.setText("");
        txtCosto.setText("");
        
        modLibro.clear();
        modEditorial.clear(); 
        modClase.clear(); 
        modAnio.clear(); 
        modPaginas.clear(); 
        modCosto.clear();
        
        Libro.limpiarEstaticos();
        
        modEstadisticas.clear();
        
        txtLibro.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    //Métodos que obtienen los valores ingresados y seleccionados por el usuario
    
    String getLibro(){
        return txtLibro.getText();
    }
    
    String getEditorial(){
        return String.valueOf(cboEditorial.getSelectedItem());
    }
    
    String getClase(){
        return String.valueOf(cboClase.getSelectedItem());
    }
    
    int getAnio(){
        return Integer.parseInt(txtAnio.getText());
    }
    
    int getPaginas(){
       return Integer.parseInt(txtPaginas.getText());
    }
    
    double getCosto(){
        return Double.parseDouble(txtCosto.getText());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboClase;
    private javax.swing.JComboBox<String> cboEditorial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblTitReg;
    private javax.swing.JList<String> lstAnio;
    private javax.swing.JList<String> lstClase;
    private javax.swing.JList<String> lstCosto;
    private javax.swing.JList<String> lstEditorial;
    private javax.swing.JList<String> lstEstadisticas;
    private javax.swing.JList<String> lstLibro;
    private javax.swing.JList<String> lstPaginas;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtLibro;
    private javax.swing.JTextField txtPaginas;
    // End of variables declaration//GEN-END:variables
}
