/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFormularios;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import pClases.Alquiler;

/**
 *
 * @author Multi
 */
public class FrmAlquiler extends javax.swing.JFrame {
    DefaultListModel modResumen = new DefaultListModel();
    DefaultListModel modEstadisticas = new DefaultListModel();

    /**
     * Creates new form FrmAlquiler
     */
    public FrmAlquiler() {
        initComponents();
        llenaHabitacion();
    }
    
    void llenaHabitacion(){
        cboHabitacion.addItem("Simple");
        cboHabitacion.addItem("Doble");
        cboHabitacion.addItem("Matrimonial");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitAlq = new javax.swing.JLabel();
        cboHabitacion = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnProcesar = new javax.swing.JButton();
        txtDias = new javax.swing.JTextField();
        txtPersonas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstResumen = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEstadisticas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitAlq.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitAlq.setText("REGISTRO DE ALQUILERES");

        cboHabitacion.setBorder(javax.swing.BorderFactory.createTitledBorder("TIPO DE HABITACIÓN"));

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnProcesar.setText("PROCESAR");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        txtDias.setBorder(javax.swing.BorderFactory.createTitledBorder("DÍAS ALQUILADOS"));

        txtPersonas.setBorder(javax.swing.BorderFactory.createTitledBorder("NÚMERO DE PERSONAS"));

        jScrollPane1.setViewportView(lstResumen);

        jScrollPane2.setViewportView(lstEstadisticas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cboHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitAlq)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitAlq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPersonas)
                            .addComponent(txtDias)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(17, 17, 17)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int r = JOptionPane.showOptionDialog(this, "Estas seguro de salir...?", "Registro alquileres", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(r == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        cboHabitacion.setSelectedIndex(0);
        txtDias.setText("");
        txtPersonas.setText("");
        
        modResumen.clear();
        modEstadisticas.clear();
        
        cboHabitacion.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        if(valida().equals("")){
            Alquiler objAlquiler = new Alquiler();
            
            //Asignando los valores al objeto
            objAlquiler.setHabitacion(String.valueOf(cboHabitacion.getSelectedItem()));
            objAlquiler.setDias(Integer.parseInt(txtDias.getText()));
            objAlquiler.setPersonas(Integer.parseInt(txtPersonas.getText()));
            
            //Invocando a los procesos
            double monto = objAlquiler.calculaMonto();
            objAlquiler.conteos();
            
            int total = Alquiler.getTotal();
            int costoSimple = Alquiler.gettSimple();
            int costoDoble = Alquiler.gettDoble();
            int costoMatrimonial = Alquiler.gettMatrimonial();
            
            double porcSimple = (costoSimple * 100) / total;
            double porcDoble = (costoDoble * 100) / total;
            double porcMatrimonial = (costoMatrimonial * 100) / total;
            
            int persSimple = Alquiler.getpSimple();
            int persDoble = Alquiler.getpDoble();
            int persMatrimonial = Alquiler.getpMatrimonial();
            
            double monAcuSimple = Alquiler.getmSimple();
            double monAcuDoble = Alquiler.getmDoble();
            double monAcuMatrimonial = Alquiler.getmMatrimonial();
            
            //Imprimir
            modResumen.clear();
            modResumen.addElement("HABITACIÓN: " + objAlquiler.getHabitacion());
            modResumen.addElement("COSTO: $" + String.format("%.2f", objAlquiler.asignaCosto()));
            modResumen.addElement("No. DÍAS: " + objAlquiler.getDias());
            modResumen.addElement("-----------------------------------");
            modResumen.addElement("MONTO A PAGAR: " + String.format("%.2f", monto));
            lstResumen.setModel(modResumen);
            
            modEstadisticas.clear();
            modEstadisticas.addElement("Total de alquiler: " + total);
            modEstadisticas.addElement("Total alquiler simple: " + costoSimple);
            modEstadisticas.addElement("Total alquiler doble: " + costoDoble);
            modEstadisticas.addElement("Total alquiler matrimonial: " + costoMatrimonial);
            modEstadisticas.addElement("-----------------------------------------------");
            modEstadisticas.addElement("Porcentaje de alquiler simple: " + porcSimple);
            modEstadisticas.addElement("Porcentaje de alquiler doble: " + porcDoble);
            modEstadisticas.addElement("Porcentaje de alquiler matrimonial: " + porcMatrimonial);
            modEstadisticas.addElement("-----------------------------------------------");
            modEstadisticas.addElement("Total de personas hospedadas en simple: " + persSimple);
            modEstadisticas.addElement("Total de personas hospedadas en doble: " + persDoble);
            modEstadisticas.addElement("Total de personas hospedadas en matrimonial: " + persMatrimonial);
            modEstadisticas.addElement("-----------------------------------------------");
            modEstadisticas.addElement("Monto total en simple: " + String.format("%.2f",monAcuSimple));
            modEstadisticas.addElement("Monto total en doble: " + String.format("%.2f",monAcuDoble));
            modEstadisticas.addElement("Monto total en matrimonial: " + String.format("%.2f",monAcuMatrimonial));
            lstEstadisticas.setModel(modEstadisticas);
            
            
        }else{
            JOptionPane.showMessageDialog(null, "El problema es: \n" + valida());
        }
    }//GEN-LAST:event_btnProcesarActionPerformed
    
    String valida(){
        if( txtDias.getText().equals("") || Integer.parseInt(txtDias.getText()) < 0 ){
            return "El número de días";
        } else if( txtPersonas.getText().equals("") || Integer.parseInt(txtPersonas.getText())< 0 ){
            return "El número de personas";
        } else {
            return "";
        }
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAlquiler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboHabitacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitAlq;
    private javax.swing.JList<String> lstEstadisticas;
    private javax.swing.JList<String> lstResumen;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtPersonas;
    // End of variables declaration//GEN-END:variables
}
